# Generated by Django 4.2.20 on 2025-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Số trang'),
        ),
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày xuất bản'),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Trọng lượng (g)'),
        ),
    ]
