# Generated by Django 4.2.20 on 2025-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai2', '0005_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
