# Generated by Django 4.2.21 on 2025-05-31 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bai2', '0008_coupon_order_discount_order_final_price_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 7, 32, 39, 820182, tzinfo=datetime.timezone.utc)),
        ),
    ]
